site_name: Bali Buddy
site_url: https://balibuddy.ai

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: teal     # ocÃ©ano
      accent: amber     # sol tropical
  font:
    text: "Nunito Sans"
    code: "Fira Code"
  logo: assets/logos/mini_logo_Translucent.png
  favicon: assets/icons/favicon.ico
  features:
    - navigation.sections
    - navigation.sections
  hide:
    - search
  plugins: []
  toc:
    sidebar: false

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.1/cookieconsent.min.css
  - assets/styles/overrides.css

# Extensiones markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

# Footer
extra:
  generator: false
  copyright: >
    Â© 2025 Xift OÃœ â€“ <a href="privacy.md">Privacy Notice</a>

# Google Analytics
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.1/cookieconsent.min.js
  - assets/js/cookies.js

# Menu principal
nav:
  - ğŸŒ´ Home: '#'
  - ğŸ¤– Why Bali Buddy: '#why-bali-buddy'
  - ğŸï¸ For Tourists: '#for-tourists'
  - ğŸŒ For Expats: '#for-expats'
  - ğŸ’¼ For Businesses: '#for-businesses'
  - ğŸš€ Join: '#join-bali-buddy'
